### ISSUE TITLE
Stripe Pricing Table

### ISSUE THREAD

**Issue by ynvtlmr** [Vero-Ventures/dynamic-needs-analysis#192]
https://docs.stripe.com/no-code/pricing-table
We should probably make use of the Stripe pricing table component, instead of hard-coding the pricing options into the front-page.

**Comment by ynvtlmr** [comment]
![image](https://github.com/user-attachments/assets/15084e1a-abcb-410f-ab7f-63a2fa666bf4)

**Comment by scottchen98** [comment]
Since the activation fee is a separate product, the Stripe pricing table can't display it alongside the monthly and annual subscriptions. This creates a mismatch between what we offer (activation fee + subscription) and how the table presents it (one product per tier).
