### ISSUE TITLE
Extend the 20-year limit for assets, debts, and businesses to 50 years.

### ISSUE THREAD

**Issue by michaeleii** [Vero-Ventures/dynamic-needs-analysis#194]
All term values are "years from today", not "years from date of purchase".

**Comment by scottchen98** [comment]
The note `All term values are "years from today", not "years from date of purchase"` means that currently the terms are calculated based on the date of purchase for each asset, debt, or business. Can you reference which functions need to be updated?

**Comment by ynvtlmr** [comment]
This seems to be primarily affecting `Assets` graph output.
![image](https://github.com/user-attachments/assets/25287f96-953f-4c39-81cb-0c28707d0b7e)
Somewhere in here, we are using `yearAcquired` instead of `today`.

**Comment by ynvtlmr** [comment]
Note this file:
`src\lib\asset\utils.ts`

It may be this block here:
```
    assets.forEach((asset) => {
      if (
        year >= asset.yearAcquired &&
        year <= asset.yearAcquired + asset.term
      ) {
        yearData[toCamelCase(asset.name)] = valueAtYear(asset, year);
      }
    });
    ```
    
    specifically:
    `year <= asset.yearAcquired + asset.term`

**Comment by scottchen98** [comment]
**Before**
![Pasted Graphic](https://github.com/user-attachments/assets/b18e7a8e-1131-4ab7-b50b-a2ceaf81afe7)

**Comment by ynvtlmr** [comment]
Technically, yes. 
Although debts may be paid down to zero sooner than the official term.

**Comment by ynvtlmr** [comment]
![image](https://github.com/user-attachments/assets/c2bfc9d0-dc8f-45c5-9ed4-d927118b9603)

The term time horizon for these 4 assets is 40, 30, 20, 10 years respectively.
But the plot seems to get capped at 2050 for some reason, and the end dates do not match up.

![image](https://github.com/user-attachments/assets/c9f889b6-ec0c-4e44-b904-a8f9e1839f00)

I should expect year ends at 2034, 2044, 2054, 2064.
Instead, we have:
- tfsa - 2039
- crypto - 2044
- picasso + residence - 2050

**Comment by ynvtlmr** [comment]
![image](https://github.com/user-attachments/assets/d8625f4d-0422-4acc-8517-0f9eee67f870)

It appears to possibly work under specific conditions.
I changed them all to be purchased at the same year, and then all the years on the chart lined up properly, but now capped at 2060.
I'm guessing there is a "40 year cap" set in place for the total number of years we are charting. I suspect I put it in the original prototype to prevent the chart getting too out of hand with an asset that was to be held for 100 years or something.

![image](https://github.com/user-attachments/assets/e212b815-eff3-4457-82c8-9a12e7f3143a)

I think this is fine for now. Odds are my state had some stale data that wasn't refreshed or something.

**Comment by michaeleii** [comment]
https://github.com/Vero-Ventures/dynamic-needs-analysis/pull/206
