### ISSUE TITLE
Calculate the capital gains of a client at any given year as the total value of assets, business holdings, and debts.

### ISSUE THREAD

**Issue by michaeleii** [Vero-Ventures/dynamic-needs-analysis#196]
`net_worth = sum(assets) + sum(businesses * shares_owned_by_client) - sum(debts)`

**Comment by ynvtlmr** [comment]
IMPORTANT:
the calculation has changed significantly based on a call with Jeremy just now.
`debt` is removed from the calculation.
instead of `net worth` we want to calculate `capital gains`.

`capital_gains_at_year == value_of_asset_at_year - purchase_price_of_asset`
for a business, we do the same, and then multiple it by the `share of the business owned by the client`

**Comment by michaeleii** [comment]
> for a **business**, we do the same, and then multiple it by the `share of the business owned by the client`

Confused about this part because businesses don't have a purchase price. Is there a formula that involves the valuation and appreciation rate and term?

**Comment by ynvtlmr** [comment]
we will assume purchase price of a business is $0.
eg: if you create the business, you started it from $0.

**Comment by ynvtlmr** [comment]
![image](https://github.com/user-attachments/assets/c35c2460-6e8a-4cee-a0a0-afc79368a43b)

We will still need a way to add `insurance coverage` to the primary client, and maybe even a way to edit their `share percentage`.
I love the way you added that into the `add business` window. Very clever.
Maybe we should add the `insurance coverage` in that same `add business` window.

![image](https://github.com/user-attachments/assets/8db521d3-e97d-4d75-a37b-004cad983f12)

**Comment by ynvtlmr** [comment]
![image](https://github.com/user-attachments/assets/5151f83f-935e-45e3-a629-8eddf84fa5e6)

also, remember that we will still want to display the primary client's share value over time.
