### ISSUE TITLE
Create function to calculate the tax burden value at any give year

### ISSUE THREAD

**Issue by michaeleii** [Vero-Ventures/dynamic-needs-analysis#197]
- Chart the tax burden values for every year an asset, debt, or business is still held by the client.  
  - Display the tax burden value at `tax freeze year` on the "total needs" page as "Estate Tax Liability in X" (where X is the tax freeze year).
    - Assumption: an asset, debt, or business would be sold at the end of its term (and would therefore no longer be a tax burden).
  - Calculate the tax burden as follows:
    - `tax_bracket == bracket for net_worth at given year` (likely top tax bracket)
    - `250k * 0.5 * tax_bracket + (net_worth - 250k) * 0.67 * tax_bracket`
    - if total net worth is less than 250k, the calculation is: `net_worth * 0.5 * tax_bracket`

**Comment by ynvtlmr** [comment]
**IMPORTANT:**
Note that the tax bracket is not to be calculated on a client's `total net worth` as previously assumed, but based on `total capital gains`.
examine ticket #196 for details.
