### ISSUE TITLE
Chart `tax burden` vs `year` for all years in which we have a non-zero value, using the above function. (this is any year where there is an asset, business, or debt.

### ISSUE THREAD

**Issue by michaeleii** [Vero-Ventures/dynamic-needs-analysis#198]

**Comment by michaeleii** [comment]
Which output page would the chart be displayed in?

**Comment by ynvtlmr** [comment]
We will create a new Output section called `Net Estate` .
Put it after `Debts` and before `Goals & Philanthropy`.
If we can, add a vertical line to the chart at the `freeze year`.
