### ISSUE TITLE
Assets with float growth rate are not added

### ISSUE THREAD

**Issue by ynvtlmr** [Vero-Ventures/dynamic-needs-analysis#220]
![image](https://github.com/user-attachments/assets/b484e418-5456-430d-8f84-80e6abf90ec8)

If I set an asset with 5.5% growth rate, it will not save.
If I change it to 6% or 5%, it saves fine.
We may have a type-lock or something on floats for this input variable, either in the DB or in the code, or someplace else.

**Comment by ynvtlmr** [comment]
![image](https://github.com/user-attachments/assets/68db2d80-c34b-4bd0-b0c6-5922656395e0)

same issue exists on `Debts` too.

**Comment by michaeleii** [comment]
I think this issue is because we are using smallint as the datatype for percentage numbers in the database but we can switch to using decimal numbers. @ynvtlmr what is the preferred amount of decimal places?

**Comment by ynvtlmr** [comment]
@michaeleii I think 3 decimal places. eg: `5.125%`
anything beyond that, and it is probably made up.
