### ISSUE TITLE
Remove bug from total-needs utils.

### ISSUE THREAD

**Issue by ynvtlmr** [Vero-Ventures/dynamic-needs-analysis#234]
Remove buggy line in total-needs util file. lines 64-66
```typescript
  if (currentYear === entity.yearAcquired) {
    return parseFloat(initialValue);
  }
```

The line causes assets purchased this year to remain flat forever.

https://github.com/Vero-Ventures/dynamic-needs-analysis/blob/db0c29453755350c5bda255e749b73f1aef148aa/src/lib/total-needs/utils.ts#L64-L66

**Comment by michaeleii** [comment]
Already fixed refer: https://github.com/Vero-Ventures/dynamic-needs-analysis/pull/233

**Comment by ynvtlmr** [comment]
![image](https://github.com/user-attachments/assets/dfae794b-92fd-4794-b37e-d10f979d3a99)

Issue persists on Asset.
We have deleted it in one implementation but maintained it in another.

https://github.com/Vero-Ventures/dynamic-needs-analysis/blob/db0c29453755350c5bda255e749b73f1aef148aa/src/lib/asset/utils.ts#L9-L11

**Comment by ynvtlmr** [comment]
... sometime later, we should probably clean this up so we only maintain one version of this function.
I suspect `Business` output chart has a similar function in place.
