### ISSUE TITLE
Add PDF report output

### ISSUE THREAD

**Issue by ynvtlmr** [Vero-Ventures/dynamic-needs-analysis#243]
Create a button that says "Reporting".
The button will open a popup that will have check-boxes for each of the sections from our Outputs, with all of them selected by default.
The user may unselect sections that they are not interested in.
All checked sections will be present in the report.
The report is simply a PDF document printout, with each section on its own page / set of pages.

Report should include the sections from our Outputs in the following order:

1. Cover page - title: "<client name> Family Planning"
2. Beneficiaries
3. Assets
4. Debts
5. Income
6. Businesses
7. Goals & Philanthropy
8. Tax Exposure
9. Total Insurable Needs

**Comment by ynvtlmr** [comment]
Report outline, as described by the client:

---

PAGE 1

Smith Family Planning

- DNA branding
- date
- graphics
- Confidential 


Page 2 

Beneficiaries 

- Graph 
- Pie Chart
- Names 
- Percentages
- Equalization deficit (if any)


Page 3

Goals

- Qualitative 
- Short Term 1-3 years
- Medium term 5-10 years
- Long Term 25 years + 
- Estate Goals
- Life expectancy 


Page 4

Assets

- Values
- FMV
- ACB
- Growth Rate
- Time Horizon


Page 5

Debts

- Totals
- Interest rates
- When paid off
- Where held
- terms


Page 6 

Business information 

- Name
- Value
- ACB
- FMV
- Growth Rate
- Time Horizon


Page 7 

Shareholder Information

- Name
- Percentage
- Percentage of equity contribution 
- Graph
- Pie Chart


Page 8 

Tax summary 

- Showing capital gain exposure in any given year from now to LE
- highlight 20 years
- includes provincial 
- Shows alternatives to paying for liability 
- Graphs and Pie Charts


Page 9 

Total Needs 

- Needs
- Priorities
- Wants
- Total 
- Personal 
- Corp
- Term vs Perm

**Comment by michaeleii** [comment]
> Report outline, as described by the client:
> 
> PAGE 1
> 
> Smith Family Planning
> 
> * DNA branding
> * date
> * graphics
> * Confidential
> 
> Page 2
> 
> Beneficiaries
> 
> * Graph
> * Pie Chart
> * Names
> * Percentages
> * Equalization deficit (if any)
> 
> Page 3
> 
> Goals
> 
> * Qualitative
> * Short Term 1-3 years
> * Medium term 5-10 years
> * Long Term 25 years +
> * Estate Goals
> * Life expectancy
> 
> Page 4
> 
> Assets
> 
> * Values
> * FMV
> * ACB
> * Growth Rate
> * Time Horizon
> 
> Page 5
> 
> Debts
> 
> * Totals
> * Interest rates
> * When paid off
> * Where held
> * terms
> 
> Page 6
> 
> Business information
> 
> * Name
> * Value
> * ACB
> * FMV
> * Growth Rate
> * Time Horizon
> 
> Page 7
> 
> Shareholder Information
> 
> * Name
> * Percentage
> * Percentage of equity contribution
> * Graph
> * Pie Chart
> 
> Page 8
> 
> Tax summary
> 
> * Showing capital gain exposure in any given year from now to LE
> * highlight 20 years
> * includes provincial
> * Shows alternatives to paying for liability
> * Graphs and Pie Charts
> 
> Page 9
> 
> Total Needs
> 
> * Needs
> * Priorities
> * Wants
> * Total
> * Personal
> * Corp
> * Term vs Perm

I believe that beneficiaries allocation is in parts and not in percentages?

**Comment by ynvtlmr** [comment]
@michaeleii 
Yes, true. Parts is as it should be. No corrections there.
I wouldn't worry about it. It's a rough outline. More like suggestions.
Take it with a grain of salt, and implement the quickest most direct version of this that could be pumped out by end of day.

**Comment by michaeleii** [comment]
> @michaeleii Yes, true. Parts is as it should be. No corrections there. I wouldn't worry about it. It's a rough outline. More like suggestions. Take it with a grain of salt, and implement the quickest most direct version of this that could be pumped out by end of day.

I think we have tables outtputed but in terms of the charts they aren't rendering on the pdf viewer from `react-pdf` library. I think we might have to shift gears and do it with css hacks again.

**Comment by ynvtlmr** [comment]
@michaeleii : is this an issue with react-pdf, or with shadcn-charts, or with something else?
can we easily swap out the troublesome component to fix this? is it worth the trouble?
well the CSS hacks be sufficient to let us print the charts?
are there downsides to using these hacks that we should be aware of?
