### ISSUE TITLE
Stripe Web-hooks Failing.

### ISSUE THREAD

**Issue by ynvtlmr** [Vero-Ventures/dynamic-needs-analysis#253]
A message from Stripe from a couple hours ago:

---------

Hi there,	

We’ve had some trouble sending requests in test mode to a webhook endpoint associated with your Vero Ventures account. Stripe sends [webhook events](https://59.email.stripe.com/CL0/https:%2F%2Fstripe.com%2Fdocs%2Fwebhooks/1/01010190fc26520f-5f89cd89-6438-4af5-8e24-4152e519b640-000000/by63h4oNOzBqhD_ej6U5-cv2Fl0Zqwk_ZMYIN-lXrJo=363) to your server to notify you of activity in your Stripe account, such as a completed payout or a newly-created invoice.	

The URL of the failing webhook endpoint is: https://www.dynamicneedsanalysis.com/api/webhook	

You (or someone on your team) configured your Stripe account to send events to that URL. You can change your account’s webhook endpoints [from the Dashboard](https://59.email.stripe.com/CL0/https:%2F%2Fdashboard.stripe.com%2Fb%2Facct_14nZNrB6Mh2CRTYe%3Fdestination=%252Fwebhooks/1/01010190fc26520f-5f89cd89-6438-4af5-8e24-4152e519b640-000000/dgYClQA_vzYZ_ers-E0sRKCocRnTDxU4QWYykb7lsPk=363).	

In most cases, a failing webhook does not impact your payments or payouts. However:	

If you use subscriptions [we rely on your webhook endpoint](https://59.email.stripe.com/CL0/https:%2F%2Fstripe.com%2Fdocs%2Fbilling%2Fsubscriptions%2Fwebhooks%23understand/1/01010190fc26520f-5f89cd89-6438-4af5-8e24-4152e519b640-000000/DbFdTN-S9SS0xnk73OQgqOEbcgHQJk0bZydNshAVQLw=363) to notify you of new invoices. These invoices may be delayed for up to three days if your endpoint is unable to successfully receive them.

If you use Checkout and rely on the checkout.session.completed event as part of your [purchase fulfillment process](https://59.email.stripe.com/CL0/https:%2F%2Fstripe.com%2Fdocs%2Fpayments%2Fcheckout%2Ffulfillment%23webhooks/1/01010190fc26520f-5f89cd89-6438-4af5-8e24-4152e519b640-000000/_NeV66pBcS3eMNqCoFCdFgu4Dh7zx3XmdKsyiPM-NGY=363), you should review your completed payments to ensure you have fulfilled all recent purchases.

We’ve attempted to send event notifications to this endpoint 7 times since the first failure on July 26, 2024 at 1:40:25 AM UTC. If this endpoint is important to your application, please try and fix the issue. If you do not need this webhook endpoint, you can remove it from your Stripe webhook [settings](https://59.email.stripe.com/CL0/https:%2F%2Fdashboard.stripe.com%2Fb%2Facct_14nZNrB6Mh2CRTYe%3Fdestination=%252Fwebhooks/2/01010190fc26520f-5f89cd89-6438-4af5-8e24-4152e519b640-000000/2oK7PgTdsjZvQBYfSZ8fbj3KymlQo2hPt2Fk57TSv3s=363). We will stop sending event notifications to this webhook endpoint by August 4, 2024 at 1:40:25 AM UTC.	

Here is the summary of errors we received while attempting to send webhook events:	

7 requests had other errors while sending the webhook event.	

You need to return any status code between HTTP 200 to 299 for Stripe to consider the webhook event successfully delivered.	

For more details on these errors and to review your account’s recent activity, you can find the full set of [events](https://59.email.stripe.com/CL0/https:%2F%2Fdashboard.stripe.com%2Fb%2Facct_14nZNrB6Mh2CRTYe%3Fdestination=%252Ftest%252Fevents/1/01010190fc26520f-5f89cd89-6438-4af5-8e24-4152e519b640-000000/nsRYmSfp7XpVb7jxsdc-GEBB-HvPV-nvQa2UBpwmOnM=363) and [request logs](https://59.email.stripe.com/CL0/https:%2F%2Fdashboard.stripe.com%2Fb%2Facct_14nZNrB6Mh2CRTYe%3Fdestination=%252Ftest%252Flogs/1/01010190fc26520f-5f89cd89-6438-4af5-8e24-4152e519b640-000000/l1QqTEwjtI5XE3sbRlYzcj98nn-RX4H-rcM9_Ctnja8=363) on the Dashboard.	
 
For more in-depth information on how to use webhooks, we recommend reviewing our [documentation](https://59.email.stripe.com/CL0/https:%2F%2Fstripe.com%2Fdocs%2Fwebhooks/2/01010190fc26520f-5f89cd89-6438-4af5-8e24-4152e519b640-000000/E3E-_cEuqPMxLHCZ43J0avYhmH-4mrltGx0eEbmNx34=363).	

Yours,	

The Stripe team

**Comment by scottchen98** [comment]
@ynvtlmr , we're currently not using this webhook endpoint in Vero Ventures account, so the failure isn't critical. I can remove it for now.
