### ISSUE TITLE
New income replacement multiplier calculation.

### ISSUE THREAD

**Issue by ynvtlmr** [Vero-Ventures/dynamic-needs-analysis#276]
Official income replacement multiplier calculation.
Strictly based on `age` and `income`.

We can therefore get rid of `retirement age` as it is now irrelevant.
Technically, an advisor can fight for a higher multiple from the insurance company, but it is rare, so I would remove the `income replacement  multiplier` from the inputs too.

The calculation is:
Maximum amount of personal insurance available, based on the proposed insured’s earned income, would be the higher of:
• Age 16-30: $500,000 or 30x earned income - `max(500000, 30 * income)`
• Age 31-40: $500,000 or 25x earned income - `max(500000, 25 * income)`
• Age 41-50: $500,000 or 20x earned income - `max(500000, 20 * income)`
• Age 51-60: $250,000 or 15x earned income - `max(250000, 15 * income)`
• Age 61-69: $250,000 or 10x earned income - `max(250000, 10 * income)`
• Age 70 and up: $100,000 or higher amounts will be considered on an individual basis. - `100000`

The dollar minimums on here don't actually matter much, since 500k / 20 is still 25k/year, which is above minimum wage, so basically no one but the unemployed would fall into that bucket.

![image](https://github.com/user-attachments/assets/85b3914a-6a66-4caa-88d3-e86c8d2b7041)

[SunLife - 810-3877-06-21.pdf](https://github.com/user-attachments/files/16461488/SunLife.-.810-3877-06-21.pdf)

**Comment by michaeleii** [comment]
Hey @ynvtlmr, just wanted to clarify in this issue you want us to:
- Update the income replacement calculation to the new one
- Remove retirement age
- Remove income replacement multiplier input

Did I miss anything else?

**Comment by ynvtlmr** [comment]
100% correct.
