### ISSUE TITLE
Philanthropic goals calculation

### ISSUE THREAD

**Issue by ynvtlmr** [Vero-Ventures/dynamic-needs-analysis#277]
Official calculation for charitable donations:

Most proposed insureds will be eligible for $100,000, as long as they have some existing personal insurance coverage.
Higher amounts will be considered on an individual basis. Generally, the maximum we will consider, is an amount equivalent to 25% of the proposed insured’s net worth, as long as their personal insurance needs are met.

`max(100000, 0.25 * net_worth)`

any value added to `charitable goals` as an insurance need is subtracted from their personal `estate tax` need.

![image](https://github.com/user-attachments/assets/9865f8fa-2128-4024-a251-dee4c523f368)

[SunLife - 810-3877-06-21.pdf](https://github.com/user-attachments/files/16461549/SunLife.-.810-3877-06-21.pdf)

**Comment by michaeleii** [comment]
@ynvtlmr Which page do you want this displayed?

**Comment by ynvtlmr** [comment]
Add it to the goals output page as another row on the table.
Make it something like `max insurable charitable donations`.

**Comment by michaeleii** [comment]
> any value added to `charitable goals` as an insurance need is subtracted from their personal `estate tax` need.

@ynvtlmr 

- How do we determine whether the goal is an insurance need? 
- How to determine the value for estate tax need?

**Comment by ynvtlmr** [comment]
from what I gather, this is only applicable for charitable goals to charities where a person has already contributed in the past.
it also appears that it is not an additional insurable need, but rather a re-allocation of funds from one insurance bucket to another.
let's backlog this ticket for now. it needs more clarity from the client before we actually implement anything.
