### ISSUE TITLE
Rename `Shareholders Agreement` to `Buy Sell Shareholders Agreement` on `total needs` page.

### ISSUE THREAD

**Issue by ynvtlmr** [Vero-Ventures/dynamic-needs-analysis#278]
Rename `Shareholders Agreement` to `Buy Sell Shareholders Agreement` on `total needs` page.
Seems this is what they officially call it in the industry.

![image](https://github.com/user-attachments/assets/1ff0b2cc-a734-4782-81bb-9ec0a381e4ec)

[SunLife - 810-3877-06-21.pdf](https://github.com/user-attachments/files/16461582/SunLife.-.810-3877-06-21.pdf)

**Comment by michaeleii** [comment]
@ynvtlmr Do you want that with the hyphen or without `Buy-Sell` or `Buy Sell`

**Comment by ynvtlmr** [comment]
`Buy-Sell` with the hyphen.
