### ISSUE TITLE
Add `budget` page.

### ISSUE THREAD

**Issue by ynvtlmr** [Vero-Ventures/dynamic-needs-analysis#282]
Add a `budget` page that will recommend a min/max range for annual insurance premium budget.
It should roughly follow what we have in Figma.
The maximums are based on income and/or net worth.

We should pop multiple maximum values on the slider scale if we can and add & label them as:
- X% of income
- Y% of net worth

Minimum should probably be hardcoded as 5% of income

Odds are we will have to change it at some point in the future, but for now it is a good start.

For now, add it to the bottom of the `total insurable needs` page.

![image](https://github.com/user-attachments/assets/e022e244-71fc-452c-8dd8-52e94898aae5)

![image](https://github.com/user-attachments/assets/61eb049e-3752-4a47-9ae1-a64a15897947)

[SunLife - 810-3877-06-21.pdf](https://github.com/user-attachments/files/16462332/SunLife.-.810-3877-06-21.pdf)

**Comment by scottchen98** [comment]
@ynvtlmr , just to clarify:
For calculating the maximum percentage of net worth, are we using the client's current net worth, or should we consider an average or projected net worth over the 5-year period mentioned in the guidelines?

**Comment by ynvtlmr** [comment]
I believe they are talking about the average net worth of the client over the past 5 years.
For simplicity, we can simply use the net worth of the client today, since it is the most reliable data point we are likely to have.

are we able to add multiple label data points to the budget slider? eg:
- 5% of net income today
- 10% of net income today
- 10% of net worth today

... if we can, I say we pop in a few different ones, and see what sticks with the end users.

**Comment by scottchen98** [comment]
Don't think it's possible to have multiple label data points on the budget slider. Should we just use the higher value between the income-based and net worth-based calculations for the maximum budget recommendation?

**Comment by ynvtlmr** [comment]
Yes. That's probably best. 
Change the label for the maximum used, based on which calculation provides the largest value.
